// This file was autogenerated using mkcode -- handle.go
// DO NOT EDIT.
package ntdll

var (
	procNtClose = modntdll.NewProc("NtClose")
)

func NtClose(Handle Handle) NtStatus {
	r0, _, _ := procNtClose.Call(uintptr(Handle))
	return NtStatus(r0)
}
