// This file was autogenerated using go run mkcode.go -- handle.go
// DO NOT EDIT.

package ntdll

var (
	procNtClose = modntdll.NewProc("NtClose")
)

func NtClose(
	Handle Handle,
) NtStatus {
	r0, _, _ := procNtClose.Call(uintptr(Handle))
	return NtStatus(r0)
}
