// This file was autogenerated using go run mkcode.go -- misc.go
// DO NOT EDIT.

package ntdll

// Guid has been derived from the GUID struct definition.
type Guid struct {
	Data1 uint32
	Data2 uint16
	Data3 uint16
	Data4 [8]byte
}

// ListEntry has been derived from the LIST_ENTRY struct definition.
type ListEntry struct {
	Flink *ListEntry
	Blink *ListEntry
}
