// This file was autogenerated using go run mkcode.go -- rtl.go
// DO NOT EDIT.

package ntdll

import "unsafe"

var (
	procRtlDosPathNameToNtPathName_U = modntdll.NewProc("RtlDosPathNameToNtPathName_U")
)

// RtlRelativeNameU has been derived from the RTL_RELATIVE_NAME_U struct definition.
type RtlRelativeNameU struct {
	RelativeName        UnicodeString
	ContainingDirectory Handle
	CurDirRef           *RtlpCurdirRef
}

// RtlpCurdirRef has been derived from the RTLP_CURDIR_REF struct definition.
type RtlpCurdirRef struct {
	RefCount int32
	Handle   Handle
}

// OUT-parameter: NtFileName, FilePart, RelativeName.
// *OPT-parameter: FilePart, RelativeName.
func RtlDosPathNameToNtPathName_U(
	DosFileName *uint16,
	NtFileName *UnicodeString,
	FilePart *uint16,
	RelativeName *RtlRelativeNameU,
) bool {
	r0, _, _ := procRtlDosPathNameToNtPathName_U.Call(uintptr(unsafe.Pointer(DosFileName)),
		uintptr(unsafe.Pointer(NtFileName)),
		uintptr(unsafe.Pointer(FilePart)),
		uintptr(unsafe.Pointer(RelativeName)))
	return r0 != 0
}
