// This file was autogenerated using go run mkcode.go -- security.go
// DO NOT EDIT.

package ntdll

type Acl struct {
	AclRevision byte
	Sbz1        byte
	AclSize     uint16
	AceCount    uint16
	Sbz2        uint16
}

type Sid struct {
	Revision            byte
	SubAuthorityCount   byte
	IdentifierAuthority SidIdentifierAuthority
	SubAuthority        [1]uint32
}

type SidIdentifierAuthority struct {
	Value [6]byte
}

type SecurityDescriptor struct {
	Revision byte
	Sbz1     byte
	Control  SecurityDescriptorControl
	Owner    *Sid
	Group    *Sid
	Sacl     *Acl
	Dacl     *Acl
}
