//+build ignore

// simple crawler to extract Status Codes from MSDN.
package main

import (
	"bytes"
	"fmt"
	"go/format"
	"log"
	"os"
	"sort"
	"strings"
	"time"

	"github.com/PuerkitoBio/goquery"
)

const URL = "https://msdn.microsoft.com/en-us/library/cc704588.aspx"

type status struct {
	val  uint64
	name string
	desc string
}

var list = []status{}

type Uint64s []uint64

func (a Uint64s) Len() int           { return len(a) }
func (a Uint64s) Swap(i, j int)      { a[i], a[j] = a[j], a[i] }
func (a Uint64s) Less(i, j int) bool { return a[i] < a[j] }

func main() {
	doc, err := goquery.NewDocument(URL)
	if err != nil {
		log.Fatal(err)
	}

	/*
		<table Responsive="true" summary="table">
		 <tr class="thead" Responsive="true"><th scope="col">
		   <p>Return value/code</p>
		   </th><th scope="col">
		   <p>Description</p>
		   </th></tr>
		 <tr><td data-th="&#xA;   Return value/code&#xA;   ">
		  <p>0x00000000</p>
		  <p>STATUS_SUCCESS</p>
		  </td><td data-th="&#xA;   Description&#xA;   ">
		  <p>The operation completed successfully. </p>
		  </td></tr>
		 <tr><td data-th="&#xA;   Return value/code&#xA;   ">
		  <p>0x00000000</p>
		  <p>STATUS_WAIT_0</p>
		  </td><td data-th="&#xA;   Description&#xA;   ">
		  <p>The caller specified WaitAny for WaitType and one of
		  the dispatcher objects in the Object array has been set to the signaled
		  state.</p>
		  </td></tr>
	*/

	var n2s = map[uint64]string{}
	doc.Find("table tr").Each(func(i int, s *goquery.Selection) {
		if i == 0 {
			return // skip header
		}
		st := status{}

		td1 := s.Find("td")
		if td1 == nil {
			log.Println("entry ", i, "empty td")
			return
		}

		p := td1.Find("p").First()
		v := strings.TrimSpace(p.Text())
		if _, err = fmt.Sscanf(v, "0x%X", &st.val); err != nil {
			log.Println("entry ", i, err)
			return
		}
		st.name = p.Next().Text()
		n2s[st.val] = st.name // Any duplicate gets overwritten!
		st.desc = strings.Replace(td1.Next().Find("p").Text(), "\n", " ", -1)
		list = append(list, st)
	})

	// Write the header
	code := &bytes.Buffer{}
	code.WriteString("package ntdll\n")
	code.WriteString("// generated by github.com/oec/go-ntdll/statuscrawler; DO NOT EDIT\n")
	fmt.Fprintf(code, "// Extracted from %s on %s\n\n", URL, time.Now().Format(time.RFC822))

	// Write the constants
	code.WriteString("const (\n")
	for i, s := range list {
		if i == 0 {
			fmt.Fprintf(code, "%s NtStatus = 0x%08X // %s\n", s.name, s.val, s.desc)
		} else {
			fmt.Fprintf(code, "%s = 0x%08X // %s\n", s.name, s.val, s.desc)
		}
	}
	code.WriteString(")\n\n")

	var keys Uint64s
	for k := range n2s {
		keys = append(keys, k)
	}
	sort.Sort(keys)

	n2s[0x00000000] = "STATUS_SUCCESS"

	// Write the reverse-lookup-table.
	// Duplicates in the original list from MSDN have been reduced to the
	// latest value.
	code.WriteString("var ntStatus2str = map[NtStatus]string{\n")
	for _, k := range keys {
		fmt.Fprintf(code, "0x%08X : \"%s\",\n", k, n2s[k])
	}
	code.WriteString("}\n\n")

	// Write the Stringer method for NtStatus
	code.WriteString(`
func (status NtStatus) String() string {
	return ntStatus2str[status]
}
	`)

	out, err := format.Source(code.Bytes())
	if err != nil {
		log.Println(err)
		log.Println(code.String())
	}

	if f, err := os.Create("ntstatus_generated.go"); err != nil {
		log.Fatal(err)
	} else if n, err := f.Write(out); err != nil {
		log.Fatal(err)
	} else if n != len(out) {
		log.Fatal("output size mismatch")
	} else {
		f.Close()
	}
}
