// This file was autogenerated using go run mkcode.go -- systeminformation.go
// DO NOT EDIT.

package ntdll

import "unsafe"

// The SystemInformationClass constants have been derived from the SYSTEM_INFORMATION_CLASS enum definition.
type SystemInformationClass uint32

const (
	SystemBasicInformation                SystemInformationClass = 0
	SystemProcessorInformation                                   = 1
	SystemPerformanceInformation                                 = 2
	SystemTimeOfDayInformation                                   = 3
	SystemPathInformation                                        = 4
	SystemProcessInformation                                     = 5
	SystemCallCountInformation                                   = 6
	SystemDeviceInformation                                      = 7
	SystemProcessorPerformanceInformation                        = 8
	SystemFlagsInformation                                       = 9
	SystemCallTimeInformation                                    = 10
	SystemModuleInformation                                      = 11
	SystemLocksInformation                                       = 12
	SystemStackTraceInformation                                  = 13
	SystemPagedPoolInformation                                   = 14
	SystemNonPagedPoolInformation                                = 15
	SystemHandleInformation                                      = 16
	SystemObjectInformation                                      = 17
	SystemPageFileInformation                                    = 18
	SystemVdmInstemulInformation                                 = 19
	SystemVdmBopInformation                                      = 20
	SystemFileCacheInformation                                   = 21
	SystemPoolTagInformation                                     = 22
	SystemInterruptInformation                                   = 23
	SystemDpcBehaviorInformation                                 = 24
	SystemFullMemoryInformation                                  = 25
	SystemLoadGdiDriverInformation                               = 26
	SystemUnloadGdiDriverInformation                             = 27
	SystemTimeAdjustmentInformation                              = 28
	SystemSummaryMemoryInformation                               = 29
	SystemNextEventIdInformation                                 = 30
	SystemEventIdsInformation                                    = 31
	SystemCrashDumpInformation                                   = 32
	SystemExceptionInformation                                   = 33
	SystemCrashDumpStateInformation                              = 34
	SystemKernelDebuggerInformation                              = 35
	SystemContextSwitchInformation                               = 36
	SystemRegistryQuotaInformation                               = 37
	SystemExtendServiceTableInformation                          = 38
	SystemPrioritySeperation                                     = 39
	SystemPlugPlayBusInformation                                 = 40
	SystemDockInformation                                        = 41
	SystemPowerInformation                                       = 42
	SystemProcessorSpeedInformation                              = 43
	SystemCurrentTimeZoneInformation                             = 44
	SystemLookasideInformation                                   = 45
)

var (
	procNtQuerySystemInformation = modntdll.NewProc("NtQuerySystemInformation")
	procNtSetSystemInformation   = modntdll.NewProc("NtSetSystemInformation")
)

// SystemModule has been derived from the SYSTEM_MODULE struct definition.
type SystemModule struct {
	Section        *byte
	MappedBase     *byte
	ImageBase      *byte
	ImageSize      uint32
	Flags          uint32
	LoadOrderIndex uint16
	InitOrderIndex uint16
	LoadCount      uint16
	NameOffset     uint16
	Name           [256]byte
}

// SystemModuleInformationT has been derived from the SYSTEM_MODULE_INFORMATION struct definition.
type SystemModuleInformationT struct {
	ModulesCount uint32
	Modules      [1]SystemModule
}

// OUT-parameter: SystemInformation, ReturnLength.
func NtQuerySystemInformation(
	SystemInformationClass SystemInformationClass,
	SystemInformation *byte,
	SystemInformationLength uint32,
	ReturnLength *uint32,
) NtStatus {
	r0, _, _ := procNtQuerySystemInformation.Call(uintptr(SystemInformationClass),
		uintptr(unsafe.Pointer(SystemInformation)),
		uintptr(SystemInformationLength),
		uintptr(unsafe.Pointer(ReturnLength)))
	return NtStatus(r0)
}

func NtSetSystemInformation(
	SystemInformationClass SystemInformationClass,
	SystemInformation *byte,
	SystemInformationLength uint32,
) NtStatus {
	r0, _, _ := procNtSetSystemInformation.Call(uintptr(SystemInformationClass),
		uintptr(unsafe.Pointer(SystemInformation)),
		uintptr(SystemInformationLength))
	return NtStatus(r0)
}
