// This file was autogenerated using go run mkcode.go -- unicode_string.go
// DO NOT EDIT.

package ntdll

// UnicodeString has been derived from the UNICODE_STRING struct definition.
type UnicodeString struct {
	Length        uint16
	MaximumLength uint16
	Buffer        *uint16
}
