// This file was autogenerated using go run mkcode.go -- unicode_string.go
// DO NOT EDIT.

package ntdll

type UnicodeString struct {
	Length        uint16
	MaximumLength uint16
	Buffer        *uint16
}
