// This file was autogenerated using mkcode -- unicode_string.go
// DO NOT EDIT.

package ntdll

var ()

type UnicodeString struct {
	Length        uint16
	MaximumLength uint16
	Buffer        *uint16
}
